# Generated by Django 2.2.4 on 2020-05-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artworkpage', '0004_artwork_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('associated_tags', models.CharField(default='', max_length=128)),
                ('priority_level', models.PositiveIntegerField(default=3)),
                ('banner_artwork', models.ImageField(upload_to='banner')),
                ('associated_artworks', models.ManyToManyField(to='artworkpage.Artwork')),
            ],
            options={
                'verbose_name': 'artwork',
                'verbose_name_plural': 'artworks',
                'ordering': ['id'],
            },
        ),
    ]
