# Generated by Django 2.2.4 on 2020-05-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20200503_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='totalPrice',
            field=models.FloatField(default=0.0),
        ),
    ]
