# Generated by Django 2.2.4 on 2020-05-05 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20200503_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artwork_booked', to='artworkpage.Artwork'),
        ),
    ]
