# Generated by Django 2.2.4 on 2020-05-05 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20200505_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='artwork',
            new_name='artwork_booked',
        ),
    ]
