# Generated by Django 2.2.4 on 2020-05-02 14:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=8)),
                ('age', models.IntegerField(null=True)),
                ('street1', models.CharField(blank=True, max_length=512)),
                ('street2', models.CharField(blank=True, max_length=512)),
                ('suburb', models.CharField(blank=True, max_length=128)),
                ('state', models.CharField(blank=True, max_length=128)),
                ('postalCode', models.CharField(blank=True, max_length=128)),
                ('country', django_countries.fields.CountryField(default='AU', max_length=2)),
                ('phone', models.CharField(blank=True, max_length=24)),
            ],
            options={
                'verbose_name': 'AdditionalInfo',
                'verbose_name_plural': 'AdditionalInfo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='verifyCode')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('send_type', models.CharField(choices=[('register', 'register'), ('forget', 'retrieve')], max_length=10, verbose_name='verifyCodeType')),
                ('send_time', models.DateTimeField(default=datetime.datetime(2020, 5, 3, 0, 26, 49, 25636), verbose_name='sendTime')),
            ],
            options={
                'verbose_name': 'Email verification code',
                'verbose_name_plural': 'Email verification code',
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('painting', models.BooleanField(default=False)),
                ('sculpture', models.BooleanField(default=False)),
                ('photography', models.BooleanField(default=False)),
                ('calligraphy', models.BooleanField(default=False)),
                ('printmaking', models.BooleanField(default=False)),
                ('artsAndCrafts', models.BooleanField(default=False)),
                ('sealCutting', models.BooleanField(default=False)),
                ('artDesign', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('artist', models.BooleanField(default=False)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('refEmail', models.EmailField(max_length=254, null=True, unique=True)),
                ('additionalInfo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.AdditionalInfo')),
                ('interest', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Interest')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['id'],
            },
        ),
    ]
