# Generated by Django 2.2.4 on 2020-05-02 23:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 9, 25, 8, 875725), verbose_name='sendTime'),
        ),
    ]
