# Generated by Django 2.2.4 on 2020-05-03 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200503_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 19, 44, 12, 149223), verbose_name='sendTime'),
        ),
    ]
