# Generated by Django 2.2.4 on 2020-05-03 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200503_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 19, 53, 11, 47444), verbose_name='sendTime'),
        ),
    ]
