# Generated by Django 2.2.4 on 2020-05-05 03:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200505_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 5, 13, 1, 8, 317049), verbose_name='sendTime'),
        ),
    ]
