# Generated by Django 2.2.4 on 2020-05-07 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20200507_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instagram_username',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 7, 20, 28, 51, 21390), verbose_name='sendTime'),
        ),
    ]
