# Generated by Django 2.2.4 on 2020-04-25 01:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20200421_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 25, 11, 52, 6, 984760), verbose_name='sendTime'),
        ),
    ]
