# Generated by Django 2.2.4 on 2020-05-08 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20200507_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 18, 28, 8, 472529), verbose_name='sendTime'),
        ),
    ]
