# Generated by Django 2.2.4 on 2020-04-25 01:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20200425_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 25, 11, 58, 24, 313099), verbose_name='sendTime'),
        ),
    ]
