# Generated by Django 2.2.4 on 2020-05-02 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20200425_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 2, 19, 22, 2, 28849), verbose_name='sendTime'),
        ),
    ]
