# Generated by Django 2.2.4 on 2020-05-19 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20200508_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 21, 16, 57, 805665), verbose_name='sendTime'),
        ),
    ]
