# Generated by Django 2.2.4 on 2020-05-19 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20200519_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 21, 35, 57, 976952), verbose_name='sendTime'),
        ),
    ]
