# Generated by Django 2.2.4 on 2020-05-02 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworkpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
