# Generated by Django 2.2.4 on 2020-05-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworkpage', '0002_artwork_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
