# Generated by Django 2.2.4 on 2020-05-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworkpage', '0003_auto_20200503_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='tags',
            field=models.CharField(default='', max_length=128),
        ),
    ]
