# Generated by Django 2.2.4 on 2020-05-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworkpage', '0005_auto_20200507_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='length',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='width',
            field=models.FloatField(default=0),
        ),
    ]
