# Generated by Django 2.2.4 on 2020-05-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworkpage', '0006_auto_20200507_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('tags_list', models.CharField(max_length=128)),
                ('banner', models.ImageField(upload_to='banner')),
                ('artwork_list', models.ManyToManyField(related_name='artwork_category', to='artworkpage.Artwork')),
            ],
        ),
    ]
