# Generated by Django 2.2.4 on 2020-05-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworkpage', '0007_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='artwork_name_list',
            field=models.CharField(default='Noting', max_length=512),
            preserve_default=False,
        ),
    ]
