# Generated by Django 2.2.4 on 2020-05-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworkpage', '0008_category_artwork_name_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='artists_string',
            field=models.CharField(default='', max_length=512),
        ),
    ]
