# Generated by Django 2.2.4 on 2020-05-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworkpage', '0009_artwork_artists_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
